name: quikbiteapp
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  font_awesome_flutter: ^10.7.0
  provider: ^6.1.2
  chewie: ^1.7.1
  video_player: ^2.8.3
  audioplayers: ^6.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/sample1.jpg
    - assets/images/sample2.jpg
    - assets/images/sample3.jpg
    - assets/videos/sample_video.mp4
    - assets/audio/sample_audio.mp3

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: RobotoCustom
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
